//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FroxenAntiHackingEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FroxenAntiHackingEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAOx9C1hVVfr3PsCRg4AbUwSjkhITpZKiRolMjh5yHz0o3sKi0sJLjSUq54gNKtCB9Lg9aVlZWWnZjE3OpGXjtRJEBaXCS6XGTFo2w6FjadmIZrK/d619uKyf2GX+/2+e73ue/T7K2Wuv27tu73pva+3Mu5dKwZIkhdB/TZOkzZIO6dKvAJMkdeqxtZP0TtiHV282OT68euyDD+XHz5iVN3XW/Y/E594/fXqeM/6ByfGzXNPjH5oebxs5Jv6RvEmTb4iM7JgQKGJEcs/rOo7KLGr+f6TniPky/1XmL+a/9vkS/T7YR5l/Hf+1zw/hvyPmB/N4B//tOMpRNIV+FyUq8y38N3N+OP99u0j/HcnDox/KfZDV09yErAxJmvR4uPTUrQUPNL87JV0THx7UqYf0k0WSEoP4u/gu9CeKPxabpMAzRXUI5Gn+ldaH653JoydamzM1/1wc1h/Xz+koLaXyHuwVLk3itYRL17KBKe8o7Rzaps+XhksP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AntiHackingEngineHelper64 {
            get {
                return ResourceManager.GetString("AntiHackingEngineHelper64", resourceCulture);
            }
        }
    }
}
